### ISSUE TITLE
h

### ISSUE THREAD

**Issue by raspberry-hash** [Creeperman007/WarnBot#5]
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at WarnBot.DBConnector.PermCheck(UInt64 user, UInt64 guild) in C:\Users\titus\OneDrive\Desktop\WarnBot-master\source\WarnBot\DBConnector.cs:line 224
   at WarnBot.Commands.<Warn>d__0.MoveNext() in C:\Users\titus\OneDrive\Desktop\WarnBot-master\source\WarnBot\Commands.cs:line 23

**Comment by fajnyCreeper** [comment]
Hello,
looks like the bot is trying to connect to invalid database. Do you have SQL server running and database with tables properly set up?

**Comment by raspberry-hash** [comment]
I use node .
